# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.a.strova.dk
title: Amalie Stokholm
email: a@strova.dk
author: Amalie Stokholm
description: > # "Amalie Stokholm's Personal Webpage"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social:
  - icon: envelope-o
    title: email
    url: mailto:a+wp@strova.dk
    #  - icon: gitlab
    #title: gitlab
    #url: https://gitlab.com/amaliestokholm
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/amaliestokholm
  - icon: map
    title: Papers
    url: https://ui.adsabs.harvard.edu/public-libraries/VoJI-I0hQmeylc72urzhUw
  - icon: instagram
    title: instagram
    url: https://instagram.com/amalie.stokholm/
  - icon: github
    title: github
    url: https://github.com/amaliestokholm
  - icon: file-pdf-o
    title: Resume
    url: https://a.strova.dk/rsc/resume.pdf

counter:
  - title: k stars analyzed
    duration: 3000
    count: 200
    prefix: '~'
  - title: (co-)authored papers
    duration: 3000
    count: 44

carousels:
  - images:
    - image: images/carousel/mountwilson.jpg
    - image: images/carousel/aot_christmasstar2017.jpeg
    - image: images/carousel/6degofscience2018.jpeg
    - image: images/carousel/6degofscience2018_2.jpeg
    - image: images/carousel/kifwinner2023.jpg
    - image: images/carousel/kifwinner2023promo.jpg
